/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_CRPCRAWLOGABSTRACT_H_
#define JSONRPC_CPP_STUB_CRPCRAWLOGABSTRACT_H_

#include <jsonrpccpp/server.h>
#include <mrpt/web/CModularServer.h>

class CRPCRawLogAbstract : public ServerInterface<CRPCRawLogAbstract>
{
    public:
        // CRPCRawLogAbstract(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<CRPCRawLogAbstract>(conn, type)
        CRPCRawLogAbstract()
        {
            this->bindAndAddMethod(jsonrpc::Procedure("Playlist.GetPlaylists", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_ARRAY,  NULL), &CRPCRawLogAbstract::Playlist_GetPlaylistsI);
            this->bindAndAddMethod(jsonrpc::Procedure("Playlist.GetItems", jsonrpc::PARAMS_BY_POSITION, jsonrpc::JSON_OBJECT,  NULL), &CRPCRawLogAbstract::Playlist_GetItemsI);
        }

        inline virtual void Playlist_GetPlaylistsI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->Playlist_GetPlaylists();
        }
        inline virtual void Playlist_GetItemsI(const Json::Value &request, Json::Value &response)
        {
            (void)request;
            response = this->Playlist_GetItems();
        }
        virtual Json::Value Playlist_GetPlaylists() = 0;
        virtual Json::Value Playlist_GetItems() = 0;
};

#endif //JSONRPC_CPP_STUB_CRPCRAWLOGABSTRACT_H_
